---
- name: Установка CUDA
  hosts: client01
  become: yes
  tasks:
    - name: Загрузка файла cuda-ubuntu2204.pin
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
        dest: /tmp/cuda-ubuntu2204.pin

    - name: Перемещение cuda-ubuntu2204.pin в /etc/apt/preferences.d/
      command: mv /tmp/cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600

    - name: Загрузка пакета cuda-repo-ubuntu2204-12-5-local.deb
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda-repo-ubuntu2204-12-5-local_12.5.1-555.42.06-1_amd64.deb
        dest: /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.1-555.42.06-1_amd64.deb

    - name: Установка пакета cuda-repo-ubuntu2204-12-5-local.deb
      command: dpkg -i /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.1-555.42.06-1_amd64.deb
      register: install_cuda_repo
      ignore_errors: true

    - name: Копирование ключа cuda-*-keyring.gpg
      command: cp /var/cuda-repo-ubuntu2204-12-5-local/cuda-1FAB43FD-keyring.gpg /usr/share/keyrings/
      when: install_cuda_repo.rc == 0

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка cuda-toolkit-12-5
      apt:
        name: cuda-toolkit-12-5
        state: present
        update_cache: yes

