---
- name: Setup NVIDIA Docker
  hosts: client01
  become: yes
  tasks:
    - name: Download and add NVIDIA GPG key and add NVIDIA Container Toolkit repository
      ansible.builtin.shell: |
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && \
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install NVIDIA Container Toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        state: present

    - name: Configure NVIDIA runtime for Docker
      ansible.builtin.command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted


